version: '3'

services:
  mongodb:
    image: 'mongo'
    ports:
      - 27017:27017
    container_name: mongodb
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=kermit
      - MONGO_INITDB_ROOT_PASSWORD=returninn-p@ssword
    networks:
      - shared-net
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    depends_on:
      - mongodb
    networks:
      - shared-net
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: kermit
      ME_CONFIG_MONGODB_ADMINPASSWORD: returninn-p@ssword
      ME_CONFIG_BASICAUTH_USERNAME: returninn
      ME_CONFIG_BASICAUTH_PASSWORD: Return@cademy
    ports:
      - '8081:8081'
    restart: always
    volumes:
      - ./data:/data/db

  app:
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8085:8085"
    restart: always
    links:
      - mongodb
    depends_on:
      - mongodb
    networks:
      - shared-net
networks:
  shared-net:
    driver: bridge